#! /bin/bash

IFNAME=enp0s5

set -x
if [ -n "$1" ];then
#create bridge, add physical interface to bridge
	ip link set $IFNAME down
	ip link add br0 type bridge
	ip link set br0 up
	ip link set $IFNAME master br0
	ip link set $IFNAME up

#add tap device to bridge
		ip link set $1 up
		sleep 0.5s
		ip link set $1 master br0

#config ip fro bridge
		pkill -9 dhclient
	sleep 5
		dhclient -v br0

		exit 0
else
		echo "ERROR: no interface specified"
		exit 1
fi
